AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  test-api-fdepiaggio

  Sample SAM Template for test-api-fdepiaggio
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  getAllFooFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lib/resources
      Handler: getAllFoo.handle
      Runtime: nodejs10.x
      Events:
        getAllFoo:
          Type: Api
          Properties:
            Path: /foo
            Method: get
  getOneFooFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lib/resources
      Handler: getOneFoo.handle
      Runtime: nodejs10.x
      Events:
        getOneFoo:
          Type: Api
          Properties:
            Path: /foo/{id}
            Method: get
  createFooFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lib/resources
      Handler: createFoo.handle
      Runtime: nodejs10.x
      Events:
        createFoo:
          Type: Api
          Properties:
            Path: /foo
            Method: post
  editFooFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lib/resources
      Handler: editFoo.handle
      Runtime: nodejs10.x
      Events:
        editFoo:
          Type: Api
          Properties:
            Path: /foo/{id}
            Method: patch
  deleteFooFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lib/resources
      Handler: deleteFoo.handle
      Runtime: nodejs10.x
      Events:
        editFoo:
          Type: Api
          Properties:
            Path: /foo/{id}
            Method: delete

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
